projects:
  feebeeamplifyclient-dev:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: api.ts
        docsFilePath: src/graphql
        region: ap-southeast-1
        apiId: z7v7vcoczrhdlioa53a6fxygje
        maxDepth: 2
extensions:
  amplify:
    version: 3
