/* Amplify Params - DO NOT EDIT
	API_FEEBEEAMPLIFYCLIENT_FOODPOSTTABLE_ARN
	API_FEEBEEAMPLIFYCLIENT_FOODPOSTTABLE_NAME
	API_FEEBEEAMPLIFYCLIENT_GRAPHQLAPIENDPOINTOUTPUT
	API_FEEBEEAMPLIFYCLIENT_GRAPHQLAPIIDOUTPUT
	API_FEEBEEAMPLIFYCLIENT_USERTABLE_ARN
	API_FEEBEEAMPLIFYCLIENT_USERTABLE_NAME
	FUNCTION_FEEBEEAUTHPOSTCONFIRMATION_NAME
	STORAGE_S329F37960_BUCKETNAME
Amplify Params - DO NOT EDIT */

exports.handler = async (event,callback) => {
	// TODO implement
	console.log(event);
	callback(null,{
		price: "1", postId: "1",
		servings: "1",
		name: "1"
	});
};
